[package]
name = "chacha20_poly1305_psiv_reference_implementation"
version = "1.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
poly1305 = "0.8.0"
rand = "0.8.5"
rand_pcg = "0.3.1"
